### ISSUE TITLE
La validación de ci con una cadena vacía da true

### ISSUE THREAD

**Issue by Gonzalo2683** [leeway-academy/ci_php#1]
Probando la validación y encuentro que al ejecutar 

```php
$ciValidator = new CiValidator();
$ciValidator->validate_ci(""); // True de una cadena vacía.
```
Aparece el siguiente notice:
```shell
Notice: Uninitialized string offset: -1 in /var/www/html/src/ci_php/src/CiValidator.php on line 16
```
No se si es así por diseño, pero me llama la atención el comportamiento.

**Comment by mchojrin** [comment]
Gracias! La verdad es que no usé nunca este validador (Lo hice porque alguien pidió si podía traducírselo de JS)... imagino que no debería dar true con una cadena vacía... ¿te animás a armar un PR?

**Comment by Gonzalo2683** [comment]
@mchojrin si, lo único es que no quiero romper el estilo de código, se me ocurre simplemente chequear que si el valor es vacío("") directamente retornar FALSE, no se si hay una opción más elegante

**Comment by mchojrin** [comment]
@Gonzalo2683 no lo veo mal... no parece un terrible fix :p

Si te copás y le ponés los tests genial ;)
